// List of possible device names for Bluefog
int dev_max = 109;
char * device_name[] = {
"Apple iPhone 3GS",
"Apple iPhone 4",
"Apple iPhone 4S",
"BlackBerry Bold 9900",
"BlackBerry Curve 3G", 
"BlackBerry Curve 9350",
"BlackBerry Pearl 3G",
"BlackBerry Porche Design P'9981",
"BlackBerry Torch 9800",
"HTC Desire",
"HTC Desire HD",
"HTC Droid Incredible 2",
"HTC Evo 3D",
"HTC Evo Design 4G",
"HTC Hero",
"HTC Inspire 4G",
"HTC Merge",
"HTC One S",
"HTC One V",
"HTC One X",
"HTC Ozone",
"HTC Rezound",
"HTC Rhyme",
"HTC Sensation",
"HTC Status",
"HTC T-Mobile G2 Touch",
"HTC T-Mobile myTouch 4G",
"HTC T-Mobile myTouch 4G Slide",
"HTC Tattoo",
"HTC Touch Cruise",
"HTC Wildfire",
"LG Banter",
"LG Banter Touch",
"LG Chocolate Touch",
"LG Cosmos",
"LG Cosmos Touch",
"LG Muzq",
"LG myTouch Q",
"LG Optimus 4X HD",
"LG Optimus 3D Cube",
"LG Optimus 3D Max",
"LG Optimus One",
"LG Optimus 2",
"LG Optimus Slider",
"LG Optimus S",
"LG Optimus M",
"LG Optimus T",
"LG Optimus Vu",
"LG dLite",
"LG Rumor Touch",
"LG Wine 2",
"Motorola Bali",
"Motorola Brute",
"Motorola Droid 2 Global",
"Motorola Droid 3",
"Motorola Droid 4",
"Motorola Droid Bionic",
"Motorola Droid Pro",
"Motorola Droid RAZR",
"Motorola Droid RAZR Maxx",
"Motorola Droid X2",
"Motorola Electrify",
"Motorola Milestone X",
"Motorola Photon 4G",
"Motorola Triumph",
"Motorola XPRT",
"Samsung t359",
"Samsung Admire",
"Samsung Captivate",
"Samsung Captivate Glide",
"Samsung Character",
"Samsung Conquer 4G",
"Samsung Epic 4G",
"Samsung Eternity II",
"Samsung Fascinate",
"Samsung Flight II",
"Samsung Illusion",
"Samsung Indulge",
"Samsung Intensity",
"Samsung Galaxy Ace 2",
"Samsung Galaxy Attain 4G",
"Samsung Galaxy Beam",
"Samsung Galaxy Indulge",
"Samsung Galaxy mini",
"Samsung Galaxy mini 2",
"Samsung Galaxy Nexus",
"Samsung Galaxy Note",
"Samsung Galaxy Precedent",
"Samsung Galaxy Prevail",
"Samsung Galaxy S",
"Samsung Galaxy S Advance",
"Samsugn Galaxy S Aviator",
"Samsung Galaxy S Blaze 4G",
"Samsung Galaxy S Beam",
"Samsung Galaxy S II",
"Samsung Galaxy S II Skyrocket",
"Samsung Galaxy S II Skyrocket HD",
"Samsung Galaxy S Plus",
"Samsung Galaxy Y Pro",
"Samsung Stratosphere",
"Samsung Gravity Smart",
"Samsung Gusto",
"Samsung Mezmerize",
"Samsung Reality",
"Samsung Replenish",
"Samsung Repp",
"Samsung Smiley",
"Samsung Suede",
"Samsung Transform Ultra",
"Samsung Vitality"};
// EOF
